- hosts: localhost
  become: true
  vars_files:
    - vars.yml
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - name: Install dropbox role from Ansible Galaxy
      command: ansible-galaxy install {{ item }}
      with_items:
        - oefenweb.dropbox

    - name: Include the core role
      include_role:
        name: core

    - name: Include the home role
      include_role:
        name: home
      when: install_type == "home" 

    - name: Include the home role
      include_role:
        name: work
      when: install_type == "work" 

    - name: Include the home role
      include_role:
        name: wsl
      when: install_type == "wsl" 
