- hosts: localhost
  become: true
  vars_files:
    - vars.yml
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - name: Include the core role, passing the install type as an argument
      include_role:
        name: core
      vars:
        install_type: install_type

    - name: Include the home role
      include_role:
        name: home
      when: install_type == "home" 

    - include: home/cron.yml
