# Installs a cron job which checks if there is a newer version to this repo every 10 mins. Pulls if so.

- name: install cron job (ansible-pull)
  tags: home
  cron: user="ansible" name="ansible provision" minute="*/10" job="{{ pull_cmd }} > /dev/null"
