- name: Creates the ansible user and adds to sudoers
  import_tasks: users.yml

- name: Creates cron job to sync this repo every 10 mins
  import_tasks: cron.yml

- name: Installs core packages
  import_tasks: packages.yml
