- name: Creates the ansible user and adds to sudoers
  import_tasks: users.yml

- name: Creates cron job to sync this repo every 10 mins
  import_tasks: cron.yml

- name: Installs core packages
  import_tasks: packages.yml

- name: Download hack font
  get_url:
    url: https://raw.githubusercontent.com/pyrho/hack-font-ligature-nerd-font/master/font/Hack%20Regular%20Nerd%20Font%20Complete%20Mono.ttf 
    dest: /usr/share/fonts/Hack_Regular_Nerd_Font_Mono.ttf
    mode: '644'

- name: link aliases
  file:
    src: "{{ repo_dir }}/roles/core/files/aliasrc"
    path: "~{{ system_username }}/.config/aliasrc"
    state: link

- name: Setup python 
  import_tasks: python.yml

- name: Setup git
  import_tasks: git.yml

- name: Setup zsh
  import_tasks: zsh.yml

- name: Setup doom
  includ_role: doom
