- name: Install zsh
  apt:
    name: zsh

- name: clone oh-my-zsh for user
  tags:
    - skip_ansible_lint
  become: yes
  become_user: "{{ system_username }}"
  command: "git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh"
  args:
    chdir: "~{{ system_username }}"
    creates: "~/.oh-my-zsh"
- name: set permissions of oh-my-zsh for users
  become: yes
  file:
    path: '~{{ system_username }}/.oh-my-zsh'
    # Prevent the cloned repository from having insecure permissions. Failing to do
    # so causes compinit() calls to fail with "command not found: compdef" errors
    # for users with insecure umasks (e.g., "002", allowing group writability).
    mode: 'go-w'
 
- name: set default shell
  become: yes
  user:
    name: "{{ system_username }}"
    shell: /bin/zsh

- name: remove .zshrc
  file:
    path: "~{{ system_username }}/.zshrc"
    state: absent

- name: link .zshrc
  file:
    src: "{{ repo_dir }}/files/.zshrc"
    path: "~{{ system_username }}/.zshrc"
    state: link
