- name: Install doom dependencies
  apt:
    name: ripgrep
    name: fd-find

- name: Install emacs
  snap:
    name: emacs
    channel: candidate
    classic: yes

- name: Install doom with clean 
  block:
    - name: Clone doom
      tags:
        - skip_ansible_lint
      become: yes
      become_user: "{{ system_username }}"
      command: "git clone --depth 1 https://github.com/hlissner/doom-emacs ~{{ system_username }}/.emacs.d"
      args:
        chdir: "~{{ system_username }}"
        creates: "~{{ system_username }}/.emacs.d"

    - name: Install doom
      tags:
        - skip_ansible_lint
      become: yes
      become_user: "{{ system_username }}"
      shell: "yes | ~{{ system_username }}/.emacs.d/bin/doom install --no-env --no-fonts"
      args:
        chdir: "~{{ system_username }}"
  rescue:
      - name: Clean .emacs.d
        file:
          path: "~{{ system_username }}/.emacs.d"
          state: absent

- name: Clean .doom.d
  become: yes
  file:
    path: "~{{ system_username }}/.doom.d"
    state: absent
    
- name: link .doom.d
  file:
    src: "{{ repo_dir }}/roles/doom/files/.doom.d"
    path: "~{{ system_username }}/.doom.d"
    state: link

- name: link bookmarks
  file:
    src: "{{ repo_dir }}/roles/doom/files/.emacs.d/.local/etc/bookmarks"
    path: "~{{ system_username }}/.emacs.d/.local/etc/bookmarks"
    state: link
    force: true

- name: make systemd dir
  file:
    path: "~{{ system_username }}/.config/systemd/user"
    state: directory
    mode: "0775"
    
- name: cp doom service file
  copy:
    src: "{{ repo_dir }}/roles/doom/files/emacs.service"
    dest: "~{{ system_username }}/.config/systemd/user/emacs.service"

- name: Make systemd dir for enabled services
  file:
    path: "~{{ system_username }}/.config/systemd/user/default.target.wants"
    state: directory

- name: link service file
  file:
    src: "~{{ system_username }}/.config/systemd/user/emacs.service"
    path: "~{{ system_username }}/.config/systemd/user/default.target.wants/emacs.service"
    state: link
    force: true

- name: systemd reread configs
  become: yes
  become_user: "{{ system_username }}"
  systemd:
    scope: user
    daemon_reload: yes

- name: start the emacs service
  become: yes
  become_user: "{{ system_username }}"
  systemd:
    scope: user
    name: emacs
    state: started
    enabled: yes

- name: update desktop file icon path
  replace:
    path: "{{ repo_dir }}/roles/doom/files/doom.desktop"
    regexp: '^Icon=.*$'
    replace: "Icon={{ repo_dir }}/roles/doom/files/splash.png"

- name: link desktop file
  file:
    src: "{{ repo_dir }}/roles/doom/files/doom.desktop"
    path: "~{{ system_username }}/.local/share/applications/doom.desktop"
    state: link
