- name: Setup Dropbox
  include_role:
    name: oefenweb.dropbox

- name: dropbox | Install Dropbox
  shell: wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -
  args:
    chdir: "~{{ system_username }}"
    creates: "{{ system_username }}/.dropbox-dist/dropboxd"

- name: dropbox | Copy the unit file
  template:
    src: dropbox.service
    dest: "~{{ system_username }}/.config/systemd/user/dropbox.service"

- name: systemd reread configs
  become: yes
  become_user: "{{ system_username }}"
  systemd:
    scope: user
    daemon_reload: yes

- name: start the dropbox service
  become: yes
  become_user: "{{ system_username }}"
  systemd:
    scope: user
    name: dropbox
    state: started
    enabled: yes

- name: dropbox | Check dropboxd status
  command: dropbox status
  register: status

- name: dropbox | Start dropboxd
  shell: dropbox start >/dev/null 2>&1
  when: status.stdout == "Dropbox isn't running!"
